SET XACT_ABORT ON
BEGIN TRAN
use G_Ponto

INSERT INTO users([LOGIN],SENHA,DT_ACESSI,STATE_ID,COD_DEP,COD_MAIL)
select
LEFT(f.NOME,1) + +
CASE
	WHEN REPLACE(CHARINDEX(' ',REVERSE(LTRIM(RTRIM(f.SOBRE_NOME)))),' ','') > 0 THEN REPLACE(RIGHT(f.SOBRE_NOME, CHARINDEX(' ',REVERSE(LTRIM(RTRIM(SOBRE_NOME))))-0),' ','')
	ELSE ''
END AS 'LOGIN',
REPLACE(REPLACE(REPLACE(LEFT(f.NOME,2) + REPLACE(CONVERT(varchar,f.CODE),'0','') +
CASE
	WHEN REPLACE(CHARINDEX(' ',REVERSE(LTRIM(RTRIM(f.SOBRE_NOME)))),' ','') > 0 THEN REPLACE(RIGHT(f.SOBRE_NOME, CHARINDEX(' ',REVERSE(LTRIM(RTRIM(SOBRE_NOME))))-0),' ','')
	ELSE ''
END,'i','!'),'o','@'),'e','&') as SENHA,
convert(varchar,GETDATE(),103) as 'DATA_ACESSO',
1,
f.COD_DEP,
e.CODE

from funcionarios f
join emails e on e.COD_FUNC = f.CODE


--SELECT 1/0 
COMMIT TRAN
SET XACT_ABORT OFF