SET XACT_ABORT ON
BEGIN TRAN
USE G_Ponto

INSERT INTO funcionarios VALUES('Helena','da Silva cavalcante filho','1','11')
INSERT INTO funcionarios VALUES('Alice','dos Santos vilela ','1','12')
INSERT INTO funcionarios VALUES('Laura','de Oliveira carlos filho','1','11')
INSERT INTO funcionarios VALUES('Manuela','de Souza cavalcante ','1','14')
INSERT INTO funcionarios VALUES('Valentina','da Silva vilela filho','1','11')
INSERT INTO funcionarios VALUES('Sophia','de Oliveira carlos filho','1','15')
INSERT INTO funcionarios VALUES('Isabella','dos Santos marechal ','1','12')
INSERT INTO funcionarios VALUES('Miguel','de Souza cavalcante neto','1','11')
INSERT INTO funcionarios VALUES('Arthur',' Rodrigues vilela filho','1','15')
INSERT INTO funcionarios VALUES('Heitor','da Silva carlos ','1','14')
INSERT INTO funcionarios VALUES('Bernardo','dos Santos vilela filho','1','11')
INSERT INTO funcionarios VALUES('Davi','de Oliveira  ','1','15')
INSERT INTO funcionarios VALUES('Théo','dos Santos marechal neto','1','12')
INSERT INTO funcionarios VALUES('Lorenzo',' Rodrigues vilela filho','1','11')
INSERT INTO funcionarios VALUES('Heloísa','de Souza  ','1','15')
INSERT INTO funcionarios VALUES('Luiza','dos Santos cavalcante filho','1','14')
INSERT INTO funcionarios VALUES('Júlia','de Oliveira carlos ','1','11')
INSERT INTO funcionarios VALUES('Gabriel','da Silva marechal filho','1','15')
INSERT INTO funcionarios VALUES('Pedro','de Souza vilela neto','1','12')
INSERT INTO funcionarios VALUES('Benjamin','dos Santos marechal filho','1','11')
INSERT INTO funcionarios VALUES('Lorena','de Oliveira carlos ','1','14')
INSERT INTO funcionarios VALUES('Lívia','da Silva vilela filho','1','12')
INSERT INTO funcionarios VALUES('Maria Luiza','de Souza  ','1','15')
INSERT INTO funcionarios VALUES('Cecília','dos Santos carlos neto','1','11')
INSERT INTO funcionarios VALUES('Eloá','da Ferreira cavalcante filho','1','16')
INSERT INTO funcionarios VALUES('Giovanna','de Oliveira marechal ','1','17')
INSERT INTO funcionarios VALUES('Maria Clara','da Silva vilela ','1','14')
INSERT INTO funcionarios VALUES('Maria Eduarda',' Rodrigues  filho','1','12')
INSERT INTO funcionarios VALUES('Matheus','da Ferreira carlos neto','1','11')
INSERT INTO funcionarios VALUES('Lucas','de Oliveira  ','1','12')
INSERT INTO funcionarios VALUES('Nicolas','da Ferreira marechal filho','1','16')
INSERT INTO funcionarios VALUES('Joaquim','dos Santos carlos ','1','11')
INSERT INTO funcionarios VALUES('Samuel','da Silva cavalcante neto','1','17')
INSERT INTO funcionarios VALUES('Henrique','de Oliveira vilela filho','1','12')
INSERT INTO funcionarios VALUES('Rafael',' Rodrigues  ','1','11')
INSERT INTO funcionarios VALUES('Guilherme','dos Santos carlos neto','1','14')
INSERT INTO funcionarios VALUES('Mariana','da Ferreira vilela ','1','16')
INSERT INTO funcionarios VALUES('Lara',' Rodrigues  ','1','11')
INSERT INTO funcionarios VALUES('Beatriz','de Oliveira marechal neto','1','12')
INSERT INTO funcionarios VALUES('Antonella',' Pereira  ','1','14')
INSERT INTO funcionarios VALUES('Maria Júlia','de Lima cavalcante ','1','11')
INSERT INTO funcionarios VALUES('Emanuelly','da Ferreira vilela neto','1','16')
INSERT INTO funcionarios VALUES('Isadora',' Rodrigues marechal ','1','17')
INSERT INTO funcionarios VALUES('Ana Clara','da Silva  ','1','12')
INSERT INTO funcionarios VALUES('Melissa','da Ferreira cavalcante ','1','17')
INSERT INTO funcionarios VALUES('Ana Luiza','dos Santos  neto','1','16')
INSERT INTO funcionarios VALUES('Ana Júlia','de Oliveira vilela ','1','12')
INSERT INTO funcionarios VALUES('Enzo',' Pereira marechal ','1','14')
INSERT INTO funcionarios VALUES('Murilo',' Rodrigues  ','1','17')
INSERT INTO funcionarios VALUES('Enzo Gabriel','dos Santos  neto','1','12')
INSERT INTO funcionarios VALUES('Pedro Henrique','da Ferreira carlos ','1','16')
INSERT INTO funcionarios VALUES('Felipe','de Oliveira cavalcante filho','1','14')
INSERT INTO funcionarios VALUES('João Pedro',' Rodrigues  ','1','13')
INSERT INTO funcionarios VALUES('Esther','da Silva vilela neto','1','12')
INSERT INTO funcionarios VALUES('Lavínia','da Ferreira  ','1','17')
INSERT INTO funcionarios VALUES('Maitê','de Oliveira carlos ','1','13')
INSERT INTO funcionarios VALUES('Maria Cecília','dos Santos vilela ','1','16')
INSERT INTO funcionarios VALUES('Maria Alice',' Rodrigues cavalcante ','1','18')
INSERT INTO funcionarios VALUES('Sarah','da Ferreira marechal neto','1','17')
INSERT INTO funcionarios VALUES('Elisa','dos Santos vilela neto','1','16')
INSERT INTO funcionarios VALUES('Liz','de Oliveira vilela neto','1','20')
INSERT INTO funcionarios VALUES('Yasmin','da Silva  neto','1','19')
INSERT INTO funcionarios VALUES('Pietro','da Rodrigues cavalcante neto','1','16')
INSERT INTO funcionarios VALUES('Anthony','da Souza carlos ','1','17')
INSERT INTO funcionarios VALUES('Daniel','da Santos vilela ','1','18')
INSERT INTO funcionarios VALUES('Bryan','da Oliveira marechal filho','1','13')
INSERT INTO funcionarios VALUES('Davi Lucca','da Santos carlos ','1','16')
INSERT INTO funcionarios VALUES('Leonardo','da Ferreira cavalcante neto','1','19')
INSERT INTO funcionarios VALUES('Vicente','da Silva vilela ','1','16')
INSERT INTO funcionarios VALUES('Eduardo',' Pereira marechal ','1','19')
INSERT INTO funcionarios VALUES('Gael','de Souza vilela ','1','17')
INSERT INTO funcionarios VALUES('Isabelly','da Ferreira carlos ','1','13')
INSERT INTO funcionarios VALUES('Alícia','da Santos vilela neto','1','16')
INSERT INTO funcionarios VALUES('Clara','da Oliveira cavalcante filho','1','19')
INSERT INTO funcionarios VALUES('Isis','da Pereira cavalcante ','1','20')
INSERT INTO funcionarios VALUES('Rebeca','da Silva carlos ','1','17')
INSERT INTO funcionarios VALUES('Rafaela','da Souza vilela ','1','16')
INSERT INTO funcionarios VALUES('Marina','da Silva marechal ','1','13')
INSERT INTO funcionarios VALUES('Ana Laura','da Santos cavalcante ','1','19')
INSERT INTO funcionarios VALUES('Maria Helena',' Pereira vilela ','1','20')
INSERT INTO funcionarios VALUES('Agatha','de Oliveira carlos ','1','16')
INSERT INTO funcionarios VALUES('Gabriela','da Silva cavalcante ','1','17')
INSERT INTO funcionarios VALUES('Catarina','da Santos vilela ','1','13')
INSERT INTO funcionarios VALUES('Antônio','da Souza carlos neto','1','18')
INSERT INTO funcionarios VALUES('Vitor','da Oliveira marechal neto','1','17')
INSERT INTO funcionarios VALUES('João','da Santos cavalcante neto','1','13')
INSERT INTO funcionarios VALUES('João Lucas','da Pereira vilela ','1','18')
INSERT INTO funcionarios VALUES('Calebe','da Silva marechal ','1','13')
INSERT INTO funcionarios VALUES('Enrico','da Pereira vilela ','1','17')
INSERT INTO funcionarios VALUES('Vinícius','dos Santos cavalcante neto','1','19')
INSERT INTO funcionarios VALUES('Bento','da Ferreira marechal ','1','20')
INSERT INTO funcionarios VALUES('José','da Oliveira vilela filho','1','20')
INSERT INTO funcionarios VALUES('Maria','da Souza marechal ','1','17')
INSERT INTO funcionarios VALUES('Paulo','da Silva cavalcante ','1','18')
INSERT INTO funcionarios VALUES('Marli','da Santos marechal neto','1','20')
INSERT INTO funcionarios VALUES('Laissa','da Ferreira vilela ','1','19')
INSERT INTO funcionarios VALUES('Lais','da Oliveira cavalcante ','1','17')
INSERT INTO funcionarios VALUES('Larissa','da Souza marechal neto','1','19')
INSERT INTO funcionarios VALUES('Lucio','de Oliveira vilela ','1','18')
INSERT INTO funcionarios VALUES('Laercio','da Silva cavalcante filho','1','17')



--SELECT 1/0
COMMIT TRAN
SET XACT_ABORT OFF